#!/usr/bin/env python
import os
import gzip
import shutil


LOG_FILE = "/var/log/slurm/eraWrong.log"
LOG_PATH = "/var/log/slurm/"

def gzipLog():
	if os.path.exists(LOG_FILE):
		with open('%s' % LOG_FILE, 'rb') as f_in:
			with gzip.open('%s.1.gz' % LOG_FILE, 'wb') as f_out:
				shutil.copyfileobj(f_in, f_out)
		os.remove(LOG_FILE)
		

def renameLogs():
	for filename in os.listdir('%s' %LOG_PATH):
		before = os.path.join(LOG_PATH, filename) 

		if filename.startswith("eraWrong.log.2"):			
			after = os.path.join(LOG_PATH, "eraWrong.log.3.gz")
			os.rename(before, after)
		elif filename.startswith("eraWrong.log.1"):
			after = os.path.join(LOG_PATH, "eraWrong.log.2.gz")
                        os.rename(before, after)

def deleteOldLog():
	if os.path.isfile("eraWrong.log.3.gz"):
		os.remove("eraWrong.log.3.gz")


if __name__ == "__main__":
	deleteOldLog()
	renameLogs()
	gzipLog()

