#!/usr/bin/env python

import os
import sys
import subprocess
import pandas as pd
import numpy as np

def processCommands(outputList):
	p0 = subprocess.Popen(["cat", "/var/log/slurm/era.log"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=os.environ)
	output = p0.communicate()[0]

	#print output
	for idx, line in enumerate(output.splitlines()):
                outputList.append(line.split(","))

	p0.stdout.close()

def generateDataFrame(outputList):
	outputDF = pd.DataFrame(outputList, columns=['User', 'JobID', 'Steps', 'CPU', 'MemAverage', 'MemMin'])
	return outputDF

if __name__ == "__main__":
	outputList = []
	processCommands(outputList)

	if len(outputList):
		eraDF = generateDataFrame(outputList)
		#print eraDF.JobID.unique()
		#print eraDF.MemMin
		eraUniqueDF = eraDF.drop_duplicates(subset='JobID')
		eraSortDF = eraUniqueDF.sort(['JobID'])
		print eraSortDF
		
