#!/usr/bin/env python

import os
import sys
import subprocess
import pandas as pd
import numpy as np

def processCommands(outputList):
	p0 = subprocess.Popen(["cat", "/var/log/slurm/eraWrong.log"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	output = p0.communicate()[0]

	#print output
	for idx, line in enumerate(output.splitlines()):
                outputList.append(line.split(","))

	p0.stdout.close()

def generateDataFrame(outputList):
	outputDF = pd.DataFrame(outputList, columns=['Mounth', 'Day', 'Hour', 'User', 'JobID', 'Step', 'TotalStep', 'CPU', 'MemAverage', 'MemMin'])
	return outputDF

def sendMail(to, eraOutput):
	subject = "eraLog"
	cmd = """echo "{b}" | mailx -s "{s}" "{to}" 2>/dev/null""".format(
            b=eraSortDF, s=subject, to=to
        )
	os.system(cmd)	
	

if __name__ == "__main__":
	outputList = []
	processCommands(outputList)

	if len(outputList):
		eraDF = generateDataFrame(outputList)		
		eraUniqueDF = eraDF.drop_duplicates(subset='JobID')
		eraSortDF = eraUniqueDF.sort(['JobID'])
		#print eraSortDF
		
		if not eraSortDF.empty:
			for index, row in eraSortDF.iterrows():
				eraProcess = subprocess.Popen(["era", "%d" % int(row["JobID"])], stdout=subprocess.PIPE, stderr=subprocess.PIPE)				
				eraOutput = eraProcess.communicate()[0]

				#print eraOutput
				
				sendMail("hpccns@upf.edu",eraOutput)
